language: python
python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install --upgrade -r requirements/test.txt
  - pip install coveralls

script:
  - py.test --cov spd_admin --cov-config .coveragerc --cov-report term-missing

after_success:
  - coveralls
